### ISSUE TITLE
Windows Event Log permissions issue

### ISSUE THREAD

**Issue by nathanielrindlaub** [jessety/pm2-installer#40]
**Description**
I was able to install and launch a PM2 service just fine, but if I reboot the machine the PM2 service does not successfully start up again and I am getting the following error in `C:\ProgramData\pm2\service\daemon\pm2.wrapper.log`:

```
2021-08-20 10:14:06 - Failed to log event in Windows Event Log: Starting C:\Program Files\nodejs\node.exe  --harmony C:\ProgramData\npm\npm\node_modules\node-windows\lib\wrapper.js --file C:\ProgramData\pm2\service\index.js --scriptoptions= --log "PM2 wrapper" --grow 0.25 --wait 1 --maxrestarts 3 --abortonerror n --stopparentfirst true; Reason:
Message:The source was not found, but some or all event logs could not be searched.  To create the source, you need permission to read all event logs to make sure that the new source name is unique.  Inaccessible logs: Security, State.
Stacktrace:   at System.Diagnostics.EventLog.FindSourceRegistration(String source, String machineName, Boolean readOnly, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source, String machineName, Boolean wantToCreate)
   at System.Diagnostics.EventLogInternal.VerifyAndCreateSource(String sourceName, String currentMachineName)
   at System.Diagnostics.EventLogInternal.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData)
   at System.Diagnostics.EventLog.WriteEntry(String message)
   at winsw.WrapperService.LogEvent(String message)
2021-08-20 10:14:06 - Starting C:\Program Files\nodejs\node.exe  --harmony C:\ProgramData\npm\npm\node_modules\node-windows\lib\wrapper.js --file C:\ProgramData\pm2\service\index.js --scriptoptions= --log "PM2 wrapper" --grow 0.25 --wait 1 --maxrestarts 3 --abortonerror n --stopparentfirst true
```

It looks to be a permissions issue with my Local Service account? Any help would be greatly appreciated!

**Steps to Reproduce**
1. Run the following installation steps in order from an admin command prompt session:
```
npm run configure
npm run configure-policy
npm run setup
pm2 start app.js
pm2 save
```
2. Reboot computer

**Environment**
`Running on: 8/30/2021, pm2-installer 3.2.2 with node v14.17.5 and npm 6.14.14 on win32-10.0.19042.`

**Comment by ediblecode** [comment]
@nathanielrindlaub  I've had a similar thing. Here are a few ideas to maybe help you out:

Looking in event logs I'm seeing application errors for pm2.exe:

![image](https://user-images.githubusercontent.com/893676/131565739-7df033d3-8d41-40d9-98c1-d0f5fc4cf31c.png)

[this comment](https://github.com/jessety/pm2-installer/issues/19#issuecomment-806277015) suggests making sure there are permissions for local service on the PM2 folder, but that's already set for me.

I'm using Volta, so it's slightly different because of paths etc. I see this in Application logs in windows event viewer:

![image](https://user-images.githubusercontent.com/893676/131566471-6308abef-a835-4017-8e8d-23c98881f541.png)

So I suspect it's something to do with permissions on that volta folder. 

Changing the service Log On user to Local System from Local Service seems to at least make the service start, as per https://stackoverflow.com/a/46984521/486434. Hope that helps

**Comment by nathanielrindlaub** [comment]
@ediblecode - thanks for your thoughts. I was able to get it working by changing the Log On user to Local System, but it seems like there ought to be a way to get it working with the Local Service account.
